### ISSUE TITLE
Unable to install in vs2019

### ISSUE THREAD

**Issue by mhensen** [marss19/json-viewer-visual-studio-extension#5]
Can you update this extension for Visual Studio 2019?!

With kind regards,
Michael

**Comment by marss19** [comment]
Hi Michael,

Thanks for the suggestion, I'll update the extension once I have some spare time.

Kind regards,
Mykola


10 квітня 2019, 17:06:53, від mhensen <notifications@github.com>:

Can you update this extension for Visual Studio 2019?!

With kind regards,
Michael

**Comment by marss19** [comment]
Fixed.
